server:
  port: 8115
spring:
  profiles:
    active: dev
  #Configuraciones de base de datos#
  datasource:
    url: jdbc:oracle:thin:@//192.168.16.23:1521/qatmscapu.estrellaroja.com.mx
    username: PWEB
    password: pweb
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: com.ger.abordaje.config.CustomPhysicalNamingStrategy
  cloud:
    openfeign:
      client:
        config:
          ###### OPENFRIGN  SMARTMAC CLIENT ######
          tecnitrans-papeletas:
            url: "http://er-smartmac.dyndns.org:5056/WS/Papeletas_tst.php"
            connectTimeout: 500
            readTimeout: 5000
            loggerLevel: full
            requestInterceptor: com.ger.abordaje.config.FeignConfigSmartMacPapeletas
      micrometer:
        enabled: true
  #RabbitMQ configurations
  rabbitmq:
    host: 192.168.16.62
    port: 5672
    username: stratech
    password: admin
    template:
      exchange: ger.voceo

  ###### SWAGGER ######
  application:
    name: abordaje
springdoc:
  api-docs:
    path: /abordaje-docs
  swagger-ui:
    use-root-path: true
    path: /swagger-ui.html
  use-management-port: false
management:
  endpoints:
    web:
      exposure:
        include:
          - openapi
          - swagger-ui
  tracing:
    enabled: true

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){red} %clr(%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]){blue} %clr(%c{1}:){green} %clr(%m){faint}%n"
  level:
    com:
      ger:
        abordaje:
          config:
            FeignConfigSmartMacPapeletas: info

app:
  timezone: GMT-6
SMARTMAC_PAPELETAS_USER: 3strellaRoja
SMARTMAC_PAPELETAS_PASSWORD: admin2020
SMARTMAC_PAPELETAS_BEARERTOKEN: Basic M3N0cmVsbGFSb2phOmFkbWluMjAyMA==
E1_MINUTOS_ANTES: 20
E1_MINUTOS_DESPUES: 10
E2_MINUTOS_ANTES: 60
E2_MINUTOS_DESPUES: 59
E3_MINUTOS_ANTES: 61
E3_MINUTOS_DESPUES: 60
P_TARJETA_SMARTMAC: P_TARJETA_SMARTMAC
PERFIL_OPERADOR: OPERADOR
